// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9K2aTvGrYPX3G8XRjga1HNtUHWn0M72c',
    appId: '1:291768854771:web:15efceac5cc0607ff5ef86',
    messagingSenderId: '291768854771',
    projectId: 'temple-86263',
    authDomain: 'temple-86263.firebaseapp.com',
    storageBucket: 'temple-86263.appspot.com',
    measurementId: 'G-GNV2BG7JL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfsC5QNmexCMihl-GReCTjOgLTIOkNs1I',
    appId: '1:291768854771:android:b994b0d12954bb16f5ef86',
    messagingSenderId: '291768854771',
    projectId: 'temple-86263',
    storageBucket: 'temple-86263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5w3xBwAG5-RXS9l6EYZifEVMWbNpP4s',
    appId: '1:291768854771:ios:40445f88e4af8ed6f5ef86',
    messagingSenderId: '291768854771',
    projectId: 'temple-86263',
    storageBucket: 'temple-86263.appspot.com',
    iosClientId: '291768854771-2uungda8euenqktkoqekumenpoottg61.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5w3xBwAG5-RXS9l6EYZifEVMWbNpP4s',
    appId: '1:291768854771:ios:40445f88e4af8ed6f5ef86',
    messagingSenderId: '291768854771',
    projectId: 'temple-86263',
    storageBucket: 'temple-86263.appspot.com',
    iosClientId: '291768854771-2uungda8euenqktkoqekumenpoottg61.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
